ALGORITHM:
  NAME: 'BasicTransformerEncDec'

MODEL:
  NAME: 'Informer'
  SEQ_LEN: 96
  LABEL_LEN: 48
  PRED_LEN: 48
  E_LAYERS: 2
  D_LAYERS: 1
  ATTN: 'prob'
  ENC_IN: 1
  DEC_IN: 1
  C_OUT: 1

DATASETS:
  NAME: 'ETTm1'
  DATA_PATH: 'datasets/ETT/ETTm1.csv'
  FEATURES: 'S'

SOLVER:
  MAX_EPOCHS: 6

OUTPUT_DIR: "./output/ETTm1_48"